name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish
        required: true
        default: 0.20.0

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  changelog-and-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

  build-and-publish:
    runs-on: ubuntu-latest
    environment: hry
    needs: changelog-and-release
    if: ${{ needs.changelog-and-release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> "$GITHUB_PATH"
      - run: pnpm run check

      - run: |
          if echo "${{ needs.changelog-and-release.outputs.version }}" | grep -q "alpha"; then
            pnpm publish --tag alpha
          elif echo "${{ needs.changelog-and-release.outputs.version }}" | grep -q "beta"; then
            pnpm publish --tag beta
          elif echo "${{ needs.changelog-and-release.outputs.version }}" | grep -q "dev"; then
            pnpm publish --tag dev
          elif echo "${{ needs.changelog-and-release.outputs.version }}" | grep -q "rc"; then
            pnpm publish --tag rc
          else
            pnpm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MISSANNIL_HRY_TYPES_PUBLISH }}

  manual-publish:
    runs-on: ubuntu-latest
    environment: hry
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - name: Verify version
        run: test "$(node -p 'require("./package.json").version')" = "${{ inputs.version }}"
      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> "$GITHUB_PATH"
      - run: pnpm run check
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MISSANNIL_HRY_TYPES_PUBLISH }}
